apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medapp
resources:
  - namespace.yaml
  - api_gateway.yaml
  - user_service.yaml
  - doctor_service.yaml
  - nurse_service.yaml
  - hospital_service.yaml
  - booking_service.yaml
  - payment_service.yaml
  - telemedicine_service.yaml
  - notification_service.yaml
  - lab_service.yaml
  - ehr_service.yaml
  - social_service.yaml
  - analytics_service.yaml
