apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: medapp-dev
images:
  - name: REPLACE_IMAGE_REF
    newName: europe-west1-docker.pkg.dev/medapp-dev/images/api_gateway
    newTag: latest
