import type { PendingIntake, TriagePatient } from "./types";

const normalMetrics = [
  { label: "HR", value: "76", unit: "bpm", status: "normal" as const },
  { label: "BP", value: "124/78", unit: "mmHg", status: "normal" as const },
  { label: "SpO₂", value: "98%", unit: "", status: "normal" as const },
];

export const TRIAGE_PATIENTS: readonly TriagePatient[] = [
  {
    id: "amina-mensah",
    name: "Amina Mensah",
    initials: "AM",
    age: 46,
    ward: "Ward 2A",
    condition: "Shortness of breath · oxygen saturation dropped",
    clinicalNote:
      "SpO₂ improved after oxygen increase; continue monitoring and escalate if it falls below 92%.",
    level: "Critical",
    workflowStatus: "needs-review",
    conditionGroup: "Cardiology",
    updated: "Next: cardiology round 10:30",
    updatedAt: "2026-07-31T10:25:00Z",
    metrics: [
      { label: "HR · High", value: "126", unit: "bpm", status: "critical" },
      { label: "BP", value: "160/98", unit: "mmHg", status: "critical" },
      { label: "SpO₂ · low", value: "91%", unit: "", status: "critical" },
    ],
  },
  {
    id: "efua-adjei",
    name: "Efua Adjei",
    initials: "EA",
    age: 58,
    ward: "Ward 2A",
    condition: "Post-operative recovery · pain score increased",
    clinicalNote: "Review analgesia at the next round and check wound observations.",
    level: "Critical",
    workflowStatus: "needs-review",
    updated: "Next: surgical review 11:15",
    updatedAt: "2026-07-31T10:12:00Z",
    metrics: normalMetrics,
  },
  {
    id: "nana-osei",
    name: "Nana Osei",
    initials: "NO",
    age: 67,
    ward: "Ward 4B",
    condition: "Discharge plan needs clinician approval",
    clinicalNote: "Family transport has been confirmed for this afternoon.",
    level: "Stable",
    workflowStatus: "needs-review",
    updated: "Next: discharge review 12:00",
    updatedAt: "2026-07-31T10:05:00Z",
    metrics: normalMetrics,
  },
  {
    id: "kojo-darko",
    name: "Kojo Darko",
    initials: "KD",
    age: 70,
    ward: "Ward 3A",
    condition: "Blood pressure remains elevated",
    clinicalNote: "Medication dose adjusted and observation schedule is in place.",
    level: "Critical",
    workflowStatus: "up-to-date",
    updated: "Updated 28m ago",
    updatedAt: "2026-07-31T09:58:00Z",
    metrics: normalMetrics,
  },
  {
    id: "kwame-asante",
    name: "Kwame Asante",
    initials: "KA",
    age: 73,
    ward: "Ward 6C",
    condition: "Care-plan follow-up due today",
    clinicalNote: "Medication review completed. Monitor blood glucose before the evening meal.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Follow-up: bedside assessment 14:00",
    updatedAt: "2026-07-31T09:51:00Z",
    metrics: normalMetrics,
  },
  {
    id: "adwoa-boateng",
    name: "Adwoa Boateng",
    initials: "AB",
    age: 61,
    ward: "Ward 2A",
    condition: "Recovery observations are stable",
    clinicalNote: "Continue current mobilisation plan.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 41m ago",
    updatedAt: "2026-07-31T09:42:00Z",
    metrics: normalMetrics,
  },
  {
    id: "yaw-ntim",
    name: "Yaw Ntim",
    initials: "YN",
    age: 52,
    ward: "Ward 5D",
    condition: "Respiratory observations stable",
    clinicalNote: "No escalation required at this time.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 54m ago",
    updatedAt: "2026-07-31T09:29:00Z",
    metrics: normalMetrics,
  },
  {
    id: "eunice-kusi",
    name: "Eunice Kusi",
    initials: "EK",
    age: 65,
    ward: "Ward 2A",
    condition: "Physiotherapy follow-up scheduled",
    clinicalNote: "Walking distance increased this morning.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 1h ago",
    updatedAt: "2026-07-31T09:20:00Z",
    metrics: normalMetrics,
  },
  {
    id: "felix-annan",
    name: "Felix Annan",
    initials: "FA",
    age: 49,
    ward: "Ward 3A",
    condition: "Post-procedure observations stable",
    clinicalNote: "Maintain routine monitoring.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 1h ago",
    updatedAt: "2026-07-31T09:08:00Z",
    metrics: normalMetrics,
  },
  {
    id: "grace-owusu",
    name: "Grace Owusu",
    initials: "GO",
    age: 76,
    ward: "Ward 4B",
    condition: "Medication reconciliation complete",
    clinicalNote: "Pharmacy notes acknowledged.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 2h ago",
    updatedAt: "2026-07-31T08:52:00Z",
    metrics: normalMetrics,
  },
  {
    id: "henry-addo",
    name: "Henry Addo",
    initials: "HA",
    age: 57,
    ward: "Ward 5D",
    condition: "Wound care plan progressing",
    clinicalNote: "Dressing change due at 16:00.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 2h ago",
    updatedAt: "2026-07-31T08:37:00Z",
    metrics: normalMetrics,
  },
  {
    id: "irene-amoako",
    name: "Irene Amoako",
    initials: "IA",
    age: 69,
    ward: "Ward 6C",
    condition: "Nutrition review completed",
    clinicalNote: "Continue prescribed supplements.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 2h ago",
    updatedAt: "2026-07-31T08:19:00Z",
    metrics: normalMetrics,
  },
  {
    id: "joseph-arhin",
    name: "Joseph Arhin",
    initials: "JA",
    age: 64,
    ward: "Ward 4B",
    condition: "Pain management stable",
    clinicalNote: "Patient reports relief after treatment.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 3h ago",
    updatedAt: "2026-07-31T07:58:00Z",
    metrics: normalMetrics,
  },
  {
    id: "linda-quaye",
    name: "Linda Quaye",
    initials: "LQ",
    age: 55,
    ward: "Ward 3A",
    condition: "Diabetes observations reviewed",
    clinicalNote: "Continue meal-time glucose checks.",
    level: "Stable",
    workflowStatus: "up-to-date",
    updated: "Updated 3h ago",
    updatedAt: "2026-07-31T07:41:00Z",
    metrics: normalMetrics,
  },
] as const;

export const PENDING_INTAKES: readonly PendingIntake[] = [
  {
    id: "marcus-chen",
    name: "Marcus Chen",
    initials: "MC",
    referralReason: "Post-MI follow-up and medication titration.",
    referredBy: "Dr. Aris",
  },
] as const;
